### ISSUE TITLE
Requirements.bat problem.

### ISSUE THREAD

**Issue by fintan226** [THETRIPOL89/miner#1]
"pip install termcolor cryptocompare GPUtil psutil py-cpuinfo hashlib" on the requirements.bat gives me this issue, -
Requirement already satisfied: termcolor in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (1.1.0)
Collecting cryptocompare
  Using cached cryptocompare-0.7.5.tar.gz (5.2 kB)
Collecting GPUtil
  Using cached GPUtil-1.4.0.tar.gz (5.5 kB)
Requirement already satisfied: psutil in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (5.8.0)
Collecting py-cpuinfo
  Using cached py-cpuinfo-8.0.0.tar.gz (99 kB)
Collecting hashlib
  Using cached hashlib-20081119.zip (42 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ceobw8v1\\hashlib_643ccca8d3cc4c59a8522ad9eaa8258e\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ceobw8v1\\hashlib_643ccca8d3cc4c59a8522ad9eaa8258e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-ttnowd7e'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-ceobw8v1\hashlib_643ccca8d3cc4c59a8522ad9eaa8258e\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-ceobw8v1\hashlib_643ccca8d3cc4c59a8522ad9eaa8258e\setup.py", line 68
        print "unknown OS, please update setup.py"
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unknown OS, please update setup.py")?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip#sha256=419de2fd10ae71ed9c6adcb55903f116abd1d8acc8c814dfd5f839b4d5013e38 (from https://pypi.org/simple/hashlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement hashlib (from versions: 20081119)
ERROR: No matching distribution found for hashlib

**Comment by THETRIPOL89** [comment]
try doing pip3 install, instead of only pip install
